# This is a non-active comment on a separate line
imageType:
    Original: {}
    LoG: {'sigma' : [1.0, 3.0]}  # This is a non active comment on a line with active code preceding it.
    Wavelet:
        binWidth: 10

featureClass:
   shape:  
   glcm:
   glrlm: 
   firstorder: 
   glszm:
   gldm:
   ngtdm:

setting:
    normalize: True
    normalizeScale: 1
    binWidth: 25
    label: 1
    interpolator: 'sitkBSpline' # This is an enumerated value, here None is not allowed
    resampledPixelSpacing: [1, 1, 2] # This disables resampling, as it is interpreted as None, to enable it, specify spacing in x, y, z as [x, y , z]
    weightingNorm: # If no value is specified, it is interpreted as None
